config/routes.rb
Rails.application.routes.draw do

# devise-----------------------------------------------------
  # admins----------------------------------
  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }
  # users-----------------------------------
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }
#------------------------------------------------------------
  root 'home#home'

# admins--------------------------------------------

  namespace :admins do
    resources :users, only: [:index,:show,:edit,:update,:destroy,:create]
  
    resources :orders, only: [:index,:show,:update,:destroy,:create]
  
    resources :categories, only: [:index,:edit,:update,:destroy,:create]

    resources :products, only: [:index,:edit,:new,:update,:destroy,:create,:show]

    get 'homes/top'
  end

  resources :users, only: [:show, :edit, :update]
  get 'users/:id/unregister' => 'users#unregister', as: 'user_unregister'
  put 'users/:id/leave' => 'users#leave', as: 'user_leave'
  
  resources :delivery_addresses, only: [:index,:edit,:update,:destroy,:create]

  resources :products, only: [:index, :show,]

  resources :orders, only: [:index, :show, :new, :create]
  post 'orders/confirmation' => 'orders#confirmation'
  get 'orders/completation' => 'orders#completation'

  delete 'carts/reset' => 'carts#reset'
  resources :carts, only: [:index, :create, :update, :destroy]




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable

#アソシエーション----------------------------------------------------------------------
has_many :orders, dependent: :destroy
has_many :delivery_addresses, dependent: :destroy
  #カート部分--------------------------------
  has_many :carts, dependent: :destroy
  has_many :products, through: :carts
  #----------------------------------------

# validation
  validates :family_name, presence:true
  validates :first_name, presence:true
  validates :family_name_kana, presence:true
  validates :first_name_kana, presence:true
  validates :tel, presence:true
  validates :postal_code, presence:true
  validates :prefecture_code, presence:true
  validates :address_city, presence:true
  validates :address_street, presence:true
  validates :user_status, presence:true
#user_status
enum user_status:{ 有効: 0 , 退会済み: 1 }
attribute :user_status, :integer, default: 0

def active_for_authentication?
  super && (self.user_status == "有効" )
end


#  jp_prefecture用メソッド------------------------------------------------------------
include JpPrefecture
jp_prefecture :prefecture_code

def prefecture_name
 JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
end

def prefecture_name=(prefecture_name)
 self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
end
# ----------------------------------------------------------------------------------

#住所カラムの連結
def user_address
  [self.prefecture_name, self.address_city, self.address_street, self.address_building].compact.join
end
#名前の連結(使い方： @user.user_fullname →　フルネームが表示される。)
def user_fullname
  [self.family_name, self.first_name].compact.join
end

#名前カラムの連結
def user_fullname
  [self.family_name, self.first_name].compact.join
end

end

app/controllers/admins/users_controller.rb
class Admins::UsersController < ApplicationController
  before_action :authenticate_admin!
  def index
    @option = params[:option]
    if @option == "search"
      @method = params[:table]
      search = params[:search]
      if @method == "1"
        @users = User.where('family_name LIKE ?', "%#{search}%").page(params[:page]).per(10)
      else
        @users = User.where('first_name LIKE ?', "%#{search}%").page(params[:page]).per(10)
      end
    else
      @users = User.page(params[:page]).per(10)
    end

  end

  def show
  	@user =User.find(params[:id])
  end
  
  def edit
  	@user =User.find(params[:id])
  end

  def update
  	@user = User.find(params[:id])
  	if @user.update(user_params)
  		redirect_to admins_users_path
  	else
      flash[:notice]="error"
  		render "edit"
  	end
  end

  private
  def user_params
    params.require(:user).permit(:family_name,:first_name,:email,:family_name_kana,:first_name_kana,:tel,:postal_code,:prefecture_code,:address_city,:address_street,:address_building,:password,:password_confirmation,:user_status )

  end


end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  before_action :reject_user, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  def reject_user
    @user = User.find_by(email: params[:user][:email].downcase)
    if @user
      if(@user.valid_password?(params[:user][:password]) && (@user.active_for_authentication? == "有効" ))
        flash[:error] = "退会済みです。"
        redirect_to new_user_session_path
      end
    else
      flash[:error] = "必須項目を入力してください。"
    end
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!

	def show
		@user = User.find(current_user.id)
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		if @user.update(user_params)
			redirect_to user_path(current_user.id), notice: 'User was successfully created.'
		else
			render action: :edit
		end
	end

	def unregister
		@user = User.find(params[:id])
	end

	def leave
		@user = User.find(params[:id])
			# if @user.user_status == "validity"
			    @user.update(user_status: "退会済み" )
			# end
        #ログアウトさせる
        reset_session
        flash[:notice] = "ありがとうございました。またのご利用を心よりお待ちしております。"
        redirect_to root_path
	end

	private
	def user_params
		params.require(:user).permit(:family_name,:first_name,:email,:family_name_kana,:first_name_kana,:tel,:postal_code,:prefecture_code,:address_city,:address_street,:address_building,:password,:password_confirmation,:user_status )

	end
	def set_user
		@user = User.find(params[:id] || params[:user_id] )
	end
end

app/helpers/admins/users_helper.rb
module Admins::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<%= render 'layouts/header2' %>
<body style="background: #FFFF;color: #000; font-family:monospace" >
  <div class="container">
    <div class="form-group">
      <div class=col-6 style="border-bottom: 1px solid #000;border-left: 10px solid #000;padding: 7px;">
        <h3>登録情報編集</h3>
          <div class=col-6 style="opacity: 0.5; font-family:cursive" >
            <p>Edit</p>
          </div>
      </div>
    </div>


<%= form_for(@user) do |f| %>
  <%= render "devise/shared/error_messages", resource: @user %>

  <!-- name -->
<div class="form-group">
  <div class="row">
    <div class="col-3">
      <%= f.label :氏名 %><br />
    </div>
  </div>
  <div class="row">
    <div class="col-4">
      <%= f.text_field :family_name, autofocus: true, autocomplete: "family_name",class: "input form-control" %>
    </div>
      <div class="col-4">
        <%= f.text_field :first_name, autofocus: true, autocomplete: "first_name",class: "input form-control" %>
      </div>
  </div>
</div>

<!-- kana_name -->
<div class="form-group">
  <div class="row">
    <div class="col-3">
      <%= f.label :氏名（フリガナ） %><br />
    </div>
  </div>
  <div class="row">
    <div class="col-4">
      <%= f.text_field :family_name_kana, autofocus: true, autocomplete: "family_name_kana",class: "input form-control" %>
    </div>
    <div class="col-4">
      <%= f.text_field :first_name_kana, autofocus: true, autocomplete: "first_name_kana",class: "input form-control" %>
    </div>
  </div>
</div>

<!-- email -->
<div class="form-group">
  <div class="row">
    <div class="col-5">
      <%= f.label :メールアドレス %><br />
      <%= f.email_field :email, autofocus: true, autocomplete: "email",class: "input form-control" %>
    </div>
  </div>
</div>

<%= render :partial => 'layouts/addressform', :locals => {:f =>f} %>

<!-- tel -->
<div class="form-group">
  <div class="row">
    <div class="col-4">
      <%= f.label :電話番号（ハイフンなし） %><br />
      <%= f.text_field :tel, autofocus: true, autocomplete: "tel",class: "input form-control" %>
    </div>
  </div>
</div>



  <div class="form-group">
    <div class="row">
      <div class="col-3">
        <%= f.submit "編集内容を保存する",class: "btn btn-outline-dark" %>
      </div>
    </div>
  </div>
  <%= link_to "退会する",  user_unregister_path,class: "btn btn-outline-dark" %>
<% end %>

app/views/users/show.html.erb
<%= render 'layouts/header2' %>
<body style="background: #FFFF;color: #000; font-family:monospace" >
 
    <div class="form-group">
      <div class=col-6 style="border-bottom: 1px solid #000;border-left: 10px solid #000;padding: 7px;">
        <h3>マイページ</h3>
          <div class=col-6 style="opacity: 0.5; font-family:cursive" >
            <p>My page</p>
          </div>
      </div>
    </div>

    <div class="form-group">
      <div  class="row">
        <div class=col-2 style="text-align:center; padding: 10px;">
         <p>登録情報</p>
        </div>
        <div class="col-2">
          <%= link_to "編集する", edit_user_path,class: "btn btn-outline-dark" %>
        </div>
        <div class="col-4">
          <%= link_to "パスワードを変更する",  edit_user_registration_path(@user),class: "btn btn-outline-dark"%>
        </div>
      </div>
    </div>
　　 
     <table class="table table-bordered">

		<tr>
			<th bgcolor="#EEEEEE">氏名</th>
			<td><%= @user.family_name %>  <%= @user.first_name %></td>
		</tr>
		<tr>
			<th bgcolor="#EEEEEE">フリガナ</th>
			<td><%= @user.family_name_kana %>  <%= @user.first_name_kana %></td>
		</tr>
		<tr>
			<th bgcolor="#EEEEEE">郵便番号</th>
			<td><%= @user.postal_code %></td>
		</tr>
		<tr>
			<th bgcolor="#EEEEEE">住所</th>
			<td> <%= @user.user_address %> </td>
		</tr>
		<tr>
			<th bgcolor="#EEEEEE">電話番号</th>
			<td><%= @user.tel %></td>
		</tr>
		<tr>
			<th bgcolor="#EEEEEE">メールアドレス</th>
			<td><%= @user.email %></td>
		</tr>
	</table>
    
    <div class="form-group">
      <div class="row">
      	<div class=col-2 style="text-align:center; padding: 10px;">
          配送先
        </div>
        <div class="col-4">
          <%= link_to "一覧を見る", delivery_addresses_path,class: "btn btn-outline-dark", id: "delivery_link" %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <div class="row">
      	<div class=col-2 style="text-align:center; padding: 10px;">
          注文履歴
        </div>
        <div class="col-4">
          <%= link_to "一覧を見る", orders_path,class: "btn btn-outline-dark" , id: "orders_link"%>
        </div>
      </div>
  

app/views/users/unregister.html.erb
<%= render 'layouts/header2' %>
<div class="container">
		<div class="mx-auto" style="width: 800px;">
		<div class="text-center">
			<h1>本当に退会しますか？</h1>
			<h2>退会すると、会員登録情報や<br>これまでの購入履歴が閲覧できなくなります。<br>退会する場合は「退会する」をクリックしてください。</h2>
			<%= link_to "退会しない", root_path,class: "btn btn-outline-dark" %>

			<% if user_signed_in? && @user.id == current_user.id %>
			<%= link_to "退会する",user_leave_path(@user), method: :put , "data-confirm" => "本当に退会しますか？", class: "btn btn-danger" %>
			<%end%>
		</div>
	</div>
</div>