config/routes.rb
Rails.application.routes.draw do

# devise-----------------------------------------------------
  # admins----------------------------------
  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }
  # users-----------------------------------
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }
#------------------------------------------------------------
  root 'home#home'

# admins--------------------------------------------

  namespace :admins do
    resources :users, only: [:index,:show,:edit,:update,:destroy,:create]
  
    resources :orders, only: [:index,:show,:update,:destroy,:create]
  
    resources :categories, only: [:index,:edit,:update,:destroy,:create]

    resources :products, only: [:index,:edit,:new,:update,:destroy,:create,:show]

    get 'homes/top'
  end

  resources :users, only: [:show, :edit, :update]
  get 'users/:id/unregister' => 'users#unregister', as: 'user_unregister'
  put 'users/:id/leave' => 'users#leave', as: 'user_leave'
  
  resources :delivery_addresses, only: [:index,:edit,:update,:destroy,:create]

  resources :products, only: [:index, :show,]

  resources :orders, only: [:index, :show, :new, :create]
  post 'orders/confirmation' => 'orders#confirmation'
  get 'orders/completation' => 'orders#completation'

  delete 'carts/reset' => 'carts#reset'
  resources :carts, only: [:index, :create, :update, :destroy]




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  belongs_to :product

  attribute :number, :integer, default: 1

  validates :number, presence:true

  def tax_included
  	self.product.product_price.to_f * 1.08
  end

  def subtotal
  	self.tax_included * self.number
  end
  
  # def total_price(carts)
  # 	carts.map(&:subtotal).sum.to_i
  # end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  # カートページ
  def index
    @carts = Cart.where(user_id: current_user.id)
    @total_price = @carts.map(&:subtotal).sum.to_i
  end
  #商品詳細→プルダウンの個数、保存
  def create
    @cart = Cart.new(cart_params)
    @cart.user_id = current_user.id
    @cart.product_id = params[:product_id]
    @cart.save
    redirect_to carts_path
  end

#個数変更
  def update
  	@cart = Cart.find(params[:id])
  	@cart.update(cart_params)
  	redirect_to carts_path
  end
#商品1つ削除
  def destroy
  cart = Cart.find(params[:id])
	cart.destroy
	redirect_back(fallback_location: root_path)
  end
#カートを空にする
  def reset
  	current_user.carts.destroy_all
  	redirect_back(fallback_location: root_path)
  end

  private
  def cart_params
    params.require(:cart).permit(:number)
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/index.html.erb
<%= render 'layouts/header2' %>
<!-- カートページ -->
<% if current_user.carts.count != 0 %>
<div class="row"></div>
  <div class="col-9">
    <h2>ショッピングカート<i class="fas fa-shopping-cart"></i></h2>
  </div>
  <div class="col-3"></div>
<div class="row">
  <div class="col-10">
  </div>
  <div class="col-2">
  	<%= link_to carts_reset_path, method: :delete do %>
		<button type="button" class="btn btn-danger">カートを空にする</button>
	<% end %>
  </div>
</div>
<div class="row" style="height: 20px;"></div>
<div class="row">
	<table class="table table-bordered">
		<thead class="thead-dark">
			<tr>
				<th>商品名</th>
				<th>単価</th>
				<th>数量</th>
				<th>小計</th>
				<th></th>
			</tr>
		</thead>
		<tbody>
		<% @carts.each do |cart| %>
		  <tr>
		  	<td><%= attachment_image_tag cart.product, :product_image, :fill, 100, 100, class: "img-rounded", fallback: "no_image_lg.jpg" %><%= cart.product.product_name %></td>
		  	<td><%= cart.tax_included.to_i %></td>
		  	<td>
		  		<%= form_for cart do |f| %>
		  		  <%= f.number_field :number, min: 1, max: 100, class: "cart_number" %>
		  		  <%= f.submit "変更する" %>
		  		<% end %>
		  	</td>
		  	<td><%= cart.tax_included.to_i*cart.number %></td>
		  	<td>
			  <%= link_to cart_path(cart), method: :delete do %>
			    <button type="button" class="btn btn-outline-danger">削除</button>
			  <% end %>
		  	</td>
		  </tr>
		<% end %>
		</tbody>
	</table>
</div>
<div class="row">
  <div class="col-9"></div>

  <div class="col-3">
  <table class="table table-bordered">
    <tbody>
	  <tr class="border border-primary">
		<td class="p-3 mb-2 bg-dark text-white">合計金額</td>
		<td><%= @total_price %></td>
	  </tr>
	</tbody>
  </table>
  </div>

</div>
<div class="row">
	<div class="col-4"></div>
	<div class="col-8">
	    <%= link_to new_order_path, id: "info-link" do %>
          <button type="button" class="btn btn-primary btn-lg">情報入力へ進む</button>
        <% end %>
        <%= link_to products_path, id: "shop-link" do %>
          <button type="button" class="btn btn-outline-dark btn-lg">買い物を続ける</button>
        <% end %>
	</div>
</div>

<% else %>
    <div class="row" style="height: 100px;"></div>
    <div class="row">
      <div class="col-12">
    	<h4 class="text-secondary text-center">カートは空です。</h4>
    	<p class="text-secondary text-center" style="font-size: 100px;"><i class="fas fa-shopping-cart"></i></p>
      </div>
    </div>
<% end %>